### ISSUE TITLE
DDPG - Why make the agent learn on testing phase ?

### ISSUE THREAD

**Issue by khbu54efr5v14** [matinaghaei/Portfolio-Management-ActorCriticRL#3]
Hello, 

During the testing phase of the DDPG algo you made the agent learn from testset.

- Should the DDPG continue to learn during production phase ?
      - If no, why make it learn in the test phase ?
      - If yes, why not make it learn in the validation phase ?

Many thanks for taking the time to respond me

**Comment by matinaghaei** [comment]
Hi,

The purpose of the testing phase is to simulate a real scenario and see how the algorithm performs. Now, if you have a trading algorithm that is extensively trained on the market data of, for example, the past 10 years, you still let it train on the new data that is revealed on a daily basis, right? That’s why the algorithm still continues to train in the testing phase, but it’s only for one pass, unlike the training phase where it trains for multiple passes.

The purpose of the validation phase is only to see if the algorithm is overfitting the training data, not how it actually performs on the validation data in a real scenario, so I thought it was not necessary to continue training on the validation data itself, but I could do it as well.

Let me know if it makes sense to you!

**Comment by khbu54efr5v14** [comment]
Thank you for your explanations, this was very clear !

**Comment by 123456ez** [comment]
1. what is the significance of your choice of these two datasets and why is the DIJA2012 dataset for data from 1990 to 2021 and the DIJA2019 dataset for data from 2008 to 2021?
2.The result images are both for 2008 to 2021, so what is the role of the DIJA2012 data please
