### ISSUE TITLE
DDPG - Noise added during test phase

### ISSUE THREAD

**Issue by khbu54efr5v14** [matinaghaei/Portfolio-Management-ActorCriticRL#4]
Hello again, 

I see that noise is added to predicted action (mu) even during test/eval phase. 
As noise is used for exploration, shouldn't it be used only during training phase ?

Thanks

**Comment by matinaghaei** [comment]
It’s because exploration is needed for training RL agents. I don't remember the exact implementation, but I probably should have used a smaller noise for the testing phase.
